"""Debugging helpers: re-run the parser on a captured response body.

``lose-it debug parse-response FILE`` is a notebook-in-a-command. It
takes a file containing either a raw ``//OK[…]`` GWT-RPC response or
a transcript captured via ``--log-file`` (in which case it auto-extracts
the body block), and replays it through the same parser the live RPC
methods use. The output shows the resolved string table, what
``parse_response`` produced, and what the per-method parser picked —
useful when reverse-engineering edge cases where a search result picks
up the wrong brand or a diary entry comes out with the wrong meal.

Kept in its own module (and registered as a sub-app on the main CLI)
so the whole feature reverts by deleting one file + one import.
"""

from __future__ import annotations

import enum
import re
import sys
from pathlib import Path
from typing import Annotated

import typer

from ._logging import logger
from .client import Client, MissingConfigError
from .client._config import Config
from .client._gwt import parse_response
from .client.daily import parse_entries
from .client.foods import _extract_search_results, _parse_unsaved_response


class ParseMethod(enum.StrEnum):
    """Which per-method parser to run against the response body."""

    search = "search"
    unsaved = "unsaved"
    daily = "daily"


debug_app = typer.Typer(
    name="debug",
    help="Replay captured GWT-RPC responses through the parser.",
    no_args_is_help=True,
    add_completion=False,
)

# ``--log-file`` output framing — the body block starts with this marker.
_BODY_HEADER_RE = re.compile(r"── body \(\d+ bytes\) ──")
_LOG_TIMESTAMP_RE = re.compile(r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} \|", re.MULTILINE)


def _extract_response_body(text: str) -> str:
    """Pull a ``//OK[…]`` block out of ``text``.

    Accepts either a raw response (returned as-is) or a ``--log-file``
    transcript. A transcript contains TWO body sections per RPC — the
    request (a GWT-RPC envelope) and the response (``//OK[…]``) — so we
    iterate every ``── body (… bytes) ──`` marker until we find one whose
    contents begin with ``//OK`` / ``//EX``. The next log timestamp line
    bounds each body section.
    """
    if text.lstrip().startswith("//OK") or text.lstrip().startswith("//EX"):
        return text.strip()

    headers = list(_BODY_HEADER_RE.finditer(text))
    if not headers:
        raise typer.BadParameter(
            "Could not find a GWT-RPC response body. Expected the file to start "
            "with `//OK` / `//EX`, or to contain a `── body (N bytes) ──` marker "
            "from a --log-file transcript."
        )
    for header in headers:
        after = text[header.end() :]
        end = _LOG_TIMESTAMP_RE.search(after)
        body = (after[: end.start()] if end else after).strip()
        idx = body.find("//OK")
        if idx == -1:
            idx = body.find("//EX")
        if idx != -1:
            return body[idx:].strip()
    raise typer.BadParameter(
        "Found body marker(s) but no //OK / //EX inside any of them. "
        "Only request bodies were captured — re-run with --log-file after "
        "a successful RPC so the response body lands in the transcript."
    )


def _resolve_user_name(explicit: str | None) -> str:
    """Best-effort: explicit flag → config → empty.

    The parser uses ``user_name`` to filter the echoed-back username out
    of name/brand candidates. If the captured response was generated by a
    different account, override with ``--user-name``.
    """
    if explicit:
        return explicit
    try:
        return Config.from_env().user_name or ""
    except (MissingConfigError, FileNotFoundError):
        # No config on this machine? Fine — the user can still inspect a
        # response, they just lose the username-stripping heuristic.
        return ""


def _print_string_table(strings: list[str]) -> None:
    typer.echo(f"\n── String table ({len(strings)} entries) ──")
    for i, s in enumerate(strings, start=1):
        typer.echo(f"  {i:>3}  {s!r}")


def _print_token_summary(tokens: list, head: int = 30) -> None:
    typer.echo(f"\n── Tokens ({len(tokens)} total, first {head}) ──")
    for i, t in enumerate(tokens[:head]):
        typer.echo(f"  [{i:>3}] {t!r}")
    if len(tokens) > head:
        typer.echo(f"  ... {len(tokens) - head} more")


def _print_search_results(tokens: list, strings: list[str], user_name: str) -> None:
    results = _extract_search_results(tokens, strings, user_name=user_name)
    typer.echo(f"\n── searchFoods results ({len(results)}) ──")
    if not results:
        typer.echo("  (no rows extracted)")
        return
    for i, r in enumerate(results, start=1):
        typer.echo(f"  {i:>2}. name     = {r.name!r}")
        typer.echo(f"      brand    = {r.brand!r}")
        typer.echo(f"      category = {r.category!r}")
        typer.echo(f"      pk_bytes = {r.pk_bytes}")


def _print_unsaved(tokens: list, strings: list[str], user_name: str) -> None:
    u = _parse_unsaved_response(tokens, strings, user_name=user_name)
    typer.echo("\n── getUnsavedFoodLogEntry ──")
    typer.echo(f"  name                = {u.name!r}")
    typer.echo(f"  brand               = {u.brand!r}")
    typer.echo(f"  category            = {u.category!r}")
    typer.echo(f"  day_key             = {u.day_key!r}")
    typer.echo(f"  food_measure_ord    = {u.food_measure_ordinal}")
    typer.echo(f"  serving_qty         = {u.serving_qty}")
    typer.echo(f"  food_pk_bytes       = {u.food_pk_bytes}")
    typer.echo(f"  nutrients ({len(u.nutrients or {})}):")
    for ord_, val in sorted((u.nutrients or {}).items()):
        typer.echo(f"    ord={ord_:>3}  val={val}")


def _print_daily(body: str, user_name: str, hours_from_gmt: int) -> None:
    entries = parse_entries(body, default_hours_from_gmt=hours_from_gmt, user_name=user_name)
    typer.echo(f"\n── getDailyDetailsIncludingPendingForDate ({len(entries)} entries) ──")
    for i, e in enumerate(entries, start=1):
        typer.echo(
            f"  {i:>2}. meal={e.meal_ordinal} servings={e.servings} "
            f"measure_ord={e.food_measure_ordinal} name={e.food_name!r}"
        )
        typer.echo(f"      brand={e.food_brand!r} category={e.food_category!r}")
        typer.echo(f"      food_id_code={e.food_identifier_code!r}")


@debug_app.command("parse-response")
def parse_response_cmd(
    body_file: Annotated[
        Path,
        typer.Argument(
            help=(
                "File containing a raw `//OK[…]` GWT-RPC response, OR a "
                "transcript produced by `lose-it --log-file`. In the latter "
                "case the first `── body (N bytes) ──` block is extracted."
            ),
        ),
    ],
    method: Annotated[
        ParseMethod,
        typer.Option(
            "--method",
            "-m",
            help="Which per-method parser to run against the body.",
        ),
    ] = ParseMethod.search,
    user_name: Annotated[
        str | None,
        typer.Option(
            "--user-name",
            help=(
                "Override the username used by the parser's "
                "echoed-name filter. Defaults to the resolved Client config."
            ),
        ),
    ] = None,
    hours_from_gmt: Annotated[
        int,
        typer.Option(
            "--hours-from-gmt",
            help="Only used by --method daily (controls entry context fallback).",
        ),
    ] = -6,
    show_tokens: Annotated[
        bool,
        typer.Option(
            "--show-tokens/--hide-tokens",
            help="Print the first 30 raw tokens (helpful for delimiter sleuthing).",
        ),
    ] = False,
    show_strings: Annotated[
        bool,
        typer.Option(
            "--show-strings/--hide-strings",
            help="Print the full string table with 1-based indices.",
        ),
    ] = True,
) -> None:
    """Replay a captured GWT-RPC response body through the parser.

    The body can be a raw ``//OK[…]`` block (paste the response from your
    browser DevTools, or save the response part of a ``--log-file``
    transcript), or the full transcript itself — the helper auto-extracts
    the first body section in that case.

    Use this when a live ``search`` / ``log`` / ``diary`` call picked the
    wrong field and you want to see *which* string-table entries the
    parser considered, without re-firing the RPC.
    """
    text = body_file.read_text()
    body = _extract_response_body(text)
    logger.info(
        "debug.parse-response: file={f} method={m} body_size={n} chars",
        f=str(body_file),
        m=method.value,
        n=len(body),
    )

    if body.startswith("//EX"):
        typer.secho(
            f"⚠️  Body is a GWT error (//EX): {body[:200]}",
            fg=typer.colors.YELLOW,
            err=True,
        )
        raise typer.Exit(code=1)

    tokens, strings = parse_response(body)
    resolved_user = _resolve_user_name(user_name)

    typer.echo(f"File: {body_file}")
    typer.echo(f"Method: {method.value}")
    typer.echo(f"Body size: {len(body)} bytes")
    typer.echo(f"Username filter: {resolved_user!r}" if resolved_user else "Username filter: (none)")

    if show_strings:
        _print_string_table(strings)
    if show_tokens:
        _print_token_summary(tokens)

    if method is ParseMethod.search:
        _print_search_results(tokens, strings, resolved_user)
    elif method is ParseMethod.unsaved:
        _print_unsaved(tokens, strings, resolved_user)
    elif method is ParseMethod.daily:
        _print_daily(body, resolved_user, hours_from_gmt)


# Re-export ``Client`` so type-checkers/IDEs follow imports cleanly when
# the module is read in isolation.
__all__ = ["Client", "debug_app", "parse_response_cmd"]


if __name__ == "__main__":
    debug_app()
    sys.exit(0)
